name: Windows Build
on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install Dependencies
        run: |
          .\vcpkg\vcpkg install pkgconf glew glfw3 cereal wxwidgets opencv curl zlib tbb boost-system boost-filesystem boost-thread boost-log boost-locale boost-regex boost-chrono boost-atomic boost-date-time boost-iostreams --triplet x64-windows

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          $env:CMAKE_TOOLCHAIN_FILE = "../vcpkg/scripts/buildsystems/vcpkg.cmake"
          cmake .. -A x64 -DGLEW_USE_STATIC_LIBS=ON

      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BambuPlotter-Windows
          path: build/Release/BambuPlotter.exe
